middleman/middleman

- middleman-core/lib/middleman-core/core_extensions/data.rb
- middleman-core/lib/middleman-core/util.rb
- middleman-core/lib/middleman-core/util/hash_with_indifferent_access.rb
Targeting a fix for #1421, but includes changes for two issues:
- (for me at least) I would get `SystemStackErrors` running the test suite
- Util#recursively_enhance would return nil if given a string
For the first issue, I'm not sure why the Travis CI boxes never ran into it. From what I could tell anytime `respond_to?` would get triggered on `CoreExtension::Data` and the key wasn't in the `@local_data` it would raise a `SystemStackError` due to some circular calls between `data_for_path`, `respond_to?`, and `key?`.
The second, I think the history is pretty well explained in #1421. It really makes sense to me for this to be handled in one place. I initially wanted to have `Util#recursively_enhance` just call out to a class method on HashWithIndifferentAccess -- but, for now at least, …
> Standardize recursively enhance for hash with indifferent access

- middleman-core/lib/middleman-core/renderers/sass.rb
Sometimes Sprockets needs to access
`options[:custom][:sprockets_context]`. If this is set, it should not be
overridden. This happens when building a LivingStyleGuide file when the
Sass source uses `asset-path`, `image-url` or similar functions.
Background: I’m using Middleman’s Sass template to render Sass in the LivingStyleGuide. To make asset path helper functions work, I need to provide the Sprockets context. Within Rails, this works fine. But it gets overriden in Middleman. Strange thing: This only happens while building.
The error (`undefined method 'asset_path' for nil:NilClass`) happens here:
https://github.com/petebrowne/sprockets-sass/blob/master/lib/sprockets/sass/functions.rb#L36
https://github.com/petebrowne/sprockets-sass/blob/master/lib/sprockets/sass/functions.rb#L128
The …
> don’t override :custom if already set

- middleman-cli/lib/middleman-cli/init.rb
In the guide https://middlemanapp.com/basics/upgrade-v4/ it says urls without `://` are supposed to be on github, however passing the full repository url doesn't work.
```
$ middleman init -T https://github.com/middleman/middleman-templates-default.git
Template `https://github.com/middleman/middleman-templates-default.git` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?
```
I've added a way to use both middleman directory, github user/repo syntax and full clone urls (with the :// check as the guide) so all of them works.
```
middleman init -T middleman/middleman-templates-default
run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git /var/folders/dg/2k1h_3dd44b19cqk00dvs70c0000gn/T/d20150212-13109-1wnvvo2 from "."
Cloning into …
```
> Clone template from full repository urls

- middleman-cli/lib/middleman-cli/init.rb
Added also the ability to fetch ssh based git urls like `git@bitbucket.org:user/repo.git`
> Clone templates from ssh 'git@' urls

- README.md
Updating an outdated link in the README for a description of the Pessimistic Versioning Constraint.
> Fixing broken (outdated) link for the Pessimistic Versioning Constraint.

- middleman-core/lib/middleman-core/sitemap/extensions/traversal.rb
If there is a file without a basename in root, e.g. `.htaccess`,
`#parent` of another file in root finds `.htaccess` instead of
`index.html`.
Adding the `.htaccess` to the traversal-app fixture exposes this error.
The fix is to no longer scan for possible files if we know the parent
must be root.
Fixes #1463
> Fixes computation of `parent`.

- middleman-core/lib/middleman-core/builder.rb
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
- middleman-core/lib/middleman-core/extensions/relative_assets.rb
I had some 404 on my site and it was an issue with font-awesome woff2 file that didn't get the hash
> Add Woff2 to asset hash extensions

- middleman-core/lib/middleman-core/cli/build.rb
- middleman-core/lib/middleman-core/templates/html5/source/.htaccess
- middleman-core/lib/middleman-more/extensions/asset_hash.rb
Hey, I just found out that my .woff2 files do not get an assets hash. I implemented the support for it.
[Here](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a) is some information about woff 2.0.
> Append assets hash also to .woff2 files

- middleman-core/features/console.feature
- middleman-core/lib/middleman-core/cli/console.rb
This change would allow for a [cleaner][clean] implementation of the [middleman-pry][middleman-pry] extension.
[clean]: https://github.com/AndrewKvalheim/middleman-pry/commit/ba5b73a6666e4c1492c9470d762c2254f710e41a
[middleman-pry]: https://github.com/AndrewKvalheim/middleman-pry
> Move IRB initialization into a dedicated method.

- middleman-core/features/multiple-sources.feature
- middleman-core/fixtures/multiple-sources-with-duplicate-file-names-app/config.rb
- middleman-core/fixtures/multiple-sources-with-duplicate-file-names-app/source/index.html.erb
- middleman-core/fixtures/multiple-sources-with-duplicate-file-names-app/source2/index.html.erb
- middleman-core/lib/middleman-core/sources/source_watcher.rb
This change lets a source be defined with a destination directory. That way we can mount a source in a namespace and worry less about name collisions with files in other sources.
Currently if you mount a source with an `index.html`, the index at `source/index.html` gets overlooked even if they should have different destinations. The use case behind this (that I'm working on at least), would be for gem documentation -- were we're mounting the `gem_name/docs` directory with a SourceWatcher (so those files can be rendered).
> allow setting a destination_dir for SourceWatcher(s)

- middleman-core/features/content_type.feature
- middleman-core/features/minify_css.feature
- middleman-core/features/minify_javascript.feature
- middleman-core/features/support/preserve_mime_types.rb
- middleman-core/fixtures/content-type-app/source/index.php
- middleman-core/fixtures/minify-css-app/source/inline-css.php
- middleman-core/fixtures/minify-css-app/source/stylesheets/site.xcss.sass
- middleman-core/fixtures/minify-js-app/source/inline-js.php
- middleman-core/fixtures/minify-js-app/source/javascripts/js_test.xjs
- middleman-core/lib/middleman-core/core_extensions/request.rb
- middleman-core/lib/middleman-more/extensions/minify_css.rb
- middleman-core/lib/middleman-more/extensions/minify_javascript.rb
This detects minifiable content using its content type instead of file extension.
An exception is made for PHP files since they have no identifying content type. I'm wondering if it would be cleaner to just register one in Rack.
> CSS/JS isn't minified when a proxy has removed the file extension.

- CHANGELOG.md
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/cli/server.rb
- middleman-core/lib/middleman-core/preview_server.rb
The preview server can now serve over HTTPS using the `--https` flag. It will use an automatic self-signed cert which can be overridden using `--ssl_certificate` and `--ssl_private_key`. These settings can also be set in `config.rb`:
```ruby
set :https, true
set :ssl_certificate, 'server.crt'
set :ssl_private_key, 'server.key'
```
Follow [this guide from Heroku](https://devcenter.heroku.com/articles/ssl-certificate-self) to generate a custom self-signed cert.
This is very useful when your actual site will be served over HTTPS - it helps catch references to non-HTTPS resources, enables using APIs that rely on HTTPS-only cookies, and [HTTPS will be required for new web features in the future](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/).
I followed the example …
> Allow preview server to use HTTPS

- CHANGELOG.md
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/preview_server.rb
This ports commit 6a5d07028b1a211bb1bfb4b4a39575e29161e431 to `v3-stable`. It looks like at least Chrome on OS X doesn't like `0.0.0.0` URLs.
This also brings back auto-hostname-detection via `Socket.gethostname`. As I recall, the problem with that before was that on Windows, `Socket.gethostname` would return `0.0.0.0` which wouldn't load - but we've fixed that by forcing `0.0.0.0` to `localhost` so we can get our nice hostnames back now. 
Note that the changes to the preview URL (e3946a06d911fa24159e136b5b526c97d4e71d21, 8f75f6516debc28159914c79e9074d2c4e997a47) don't appear to have had a PR justifying them, nor were they mentioned on the changelog. I believe this has been broken since v3.3.2.
> Port "localhost" preview server URL to v3-stable

- CHANGELOG.md
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/cli/server.rb
- middleman-core/lib/middleman-core/preview_server.rb
Address shortcomings in #1508 by removing the "host" parameter, always binding on all interfaces, and printing the preview URL with both the local hostname and the local public IP address. As a bonus, we also gain the ability to reach the preview server over IPv6 (binding to `0.0.0.0` restricts to IPv4, while simply not passing the `:BindAddress` parameter will listen on all IPv4 and IPv6 interfaces).
One consequence (called out in the change log) is that we will no longer support the `--host` parameter since it doesn't really make sense.
I verified that I can reach the server via the provided URLs (and `localhost`) on local browsers, and via the provided URLs (but not `localhost`) via my iPhone on the same WiFi network.
Sample output on my machine:
```
== The Middleman is loading
== The …
```
> Address shortcomings in #1508

- middleman-core/features/builder.feature
- middleman-core/lib/middleman-core/builder.rb
In v3-stable branch, builded text file's permission are 0644.
But in master(v4) branch, file's permission are 0600.
When I deploy(drug-and-drop with sftp), the website isn't displayed. So
I fixed this problem.
> fixed: Builded text file(html, css, xml, txt...)'s permission is 0600

- middleman-core/lib/middleman-more/extensions/automatic_image_sizes.rb
Right now, `automatic_image_sizes` uses actual image dimensions on for the `width` and `height` properties of `<img>`, which in the case of `@2x` or even `@3x` images, is not usually intended.
This commit adds support to retina images, dividing the actual image dimensions by the `@` factor specified in the file path.
> Add retina files support on automatic_image_sizes

- middleman-core/lib/middleman-more/extensions/minify_javascript.rb
The `path` variable was being used but never defined in the context of the `minify` method. Thus, instead of a warning we would get an error. Using an instance variable fixes this.
> Allow minify to correctly throw warnings

- middleman-core/lib/middleman-core/preview_server.rb
When try to start preview server with `--port=65535` during the port 65535 is in use, the Middleman prints following messages.
```
$ bundle exec middleman --port=65535
== The Middleman is loading
== Port 65535 is unavailable. Either close the instance of Middleman already running on 65535 or start this Middleman on a new port with: --port=65536
```
The port 65535 is out of valid TCP ports range.
Additionally the middleman server doesn't avoid used port.  When the port 2999 and 3000 are in use and try to start the server with `--port=2999`,  Middleman prints --port=3000 in face of the port in use.
```
$ bundle exec middleman --port=2999
== The Middleman is loading
== Port 2999 is unavailable. Either close the instance of Middleman already running on 2999 or start this Middleman on a new …
```
> Fix port suggestion from unused ports

- middleman-core/lib/middleman-more/core_extensions/i18n.rb
The full path is now localized by build_resource, this is useful with subfolders, eg: /my/great/page -> /mon/super/site
> Added support for complete path localization

- Gemfile
- middleman-core/features/javascript-testing.feature
- middleman-core/features/support/env.rb
- middleman-core/fixtures/javascript-app/source/index.html
- middleman-core/lib/middleman-core/step_definitions/server_steps.rb
- middleman-core/middleman-core.gemspec
Hi,
with this PR we would switch from using `Rack::Test` directly, to `Capybara` + `Rack::Test` by default. This will make tests of javascript applications easier because one could use `[...]/server_steps.rb` directly.
Background:
I'm going to integrate  `mermaid` into `middleman-presentation`. `mermaid` is a `javascript`-framework to render diagram/graph-definitions. In `middleman-presentation` I use your server steps for tests. Unfortunately this doesn't work for the javascript code now.
I added a test fixture + poltergeist to make test run in background on travis. For users using the server steps: The user need to choose the capybara driver for javascript herself/himself. Will send another PR to change the documentation in `middleman-guides` if this PR is accepted.
Any suggestions? …
> Use capybara to make javascript testing possible

- middleman-core/lib/middleman-core/util.rb
line 128, Float type is also not something that can be dup'ed, similar to Fixnum and friends
> Update util.rb to support float in yaml files

- middleman-core/lib/middleman-core/sitemap/extensions/ignores.rb
This makes it match the default behaviour of Dir#glob
Edit: Ok, `uninitialized constant File::FNM_EXTGLOB (NameError)` on 1.9.3... will add an if statement.
Edit2: Amended
> Allow extended globs with ignore

- Gemfile
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/core_extensions/data.rb
- middleman-core/lib/middleman-core/core_extensions/front_matter.rb
Hey, 
This PR drops the `active_support/json` implementation in favor of the native Ruby `json` implementation. 
Quick benchmark: 
```
2.1.2 :019 > abc = {"abc" => "def", "jkl" => "mno", "pqr" => "stu", "vwx" => "yz" }
=> {"abc"=>"def", "jkl"=>"mno", "pqr"=>"stu", "vwx"=>"yz"} 
2.1.2 :020 > Benchmark.bm do |x|
2.1.2 :021 >     x.report { ActiveSupport::JSON.decode(abc.to_json) }
2.1.2 :022?>   x.report { JSON.parse(abc.to_json) }
2.1.2 :023?>   end
user     system      total        real
0.000000   0.010000   0.010000 (  0.011342)
0.000000   0.000000   0.000000 (  0.000126)
```
Also, I removed the `integer/inflections` ActiveSupport extension as it doesn't seem to be used anywhere in the current codebase. 
Cheers!
> Drop active_support's JSON in favor of native JSON implementation

- middleman-core/lib/middleman-core/step_definitions/builder_steps.rb
- middleman-core/lib/middleman-core/step_definitions/server_steps.rb
Hey, 
This PR removes most deprecation warnings from the build, as it's polluting the Travis log. They will be gone entirely after upgrading to `aruba ~> 0.8`, but this should take care of most of them.
Please check it out, thanks!
> Removed most deprecation warnings from the build.

- middleman-core/lib/middleman-core/preview_server/server_hostname.rb
Replace white space in host name to make Mac Users happy. Should help users using the new preview server version from git. Also see issue #1510
> Substitute whitespace in name

- middleman-core/lib/middleman-core/templates/shared/Gemfile.tt
As discussed https://github.com/middleman/middleman-livereload/issues/69 but I forgot to apply the fix to source code inside MM. @tdreyno, should it be `~> 3.3.0` or `~> 3.4.0`? I looked into 3.4 changes and they seem to be MM v4 related?
> Update middleman-livereload version to more current

- middleman-core/lib/middleman-core/templates/shared/gitignore
When installing gems in the local dir, the convention with Bundler is to install them in `/vendor/bundle`.
Ignoring that folder by default would be helpful to many.
> Ignore gems installed in local dir.

- middleman-core/lib/middleman-core/core_extensions/rendering.rb
I was having a problem returning `nil` from an `after_render` hook, and it looks like `content` was being set in each of these `if`/`elsif` blocks, with the result of the assignment being returned. If the hook returns `nil`, then the following statement is ineffective, since `content` is already `nil`.
```ruby
content = newcontent if newcontent # Allow the callback to return nil to skip it
```
I was seeing this surface with the following error:
```
Tried to render a layout (calls yield) at /Users/ash/bin/blog/source/blog/2015-07-27-company-values.html.markdown like it was a template. Non-default layouts need to be in source/layouts.
```
If I should add something to the changelog, let me know. I couldn't figure out the branch structure (master vs v3-stable) so I hope this is merging into …
> Fixes problem with after_render hooks returning nil.

- middleman-core/features/clean_build.feature
- middleman-core/fixtures/clean-app/config-hidden-dir-after.rb
- middleman-core/fixtures/clean-app/config-hidden-dir-before.rb
- middleman-core/lib/middleman-core/cli/build.rb
I run middleman in Jenkins. My middleman project is placed at ~/.jenkins/jobs/*/workspace and the build command can't clean files. I want to fix this.
> Fix: Can't clean files when the project is under a hidden directory.

- Rakefile
- gem_rake_helper.rb
- middleman-core/Rakefile
- middleman-core/lib/middleman-core/extensions.rb
- middleman-core/lib/middleman-core/templates/shared/config.ru
`require 'rubygems'` is already required in Ruby 1.9 or later.
> remove unnecessary require

- .gitignore
Ignore the .ruby-gemset file used to define an RVM gemset.
> Ignore .ruby-gemset file

- README.md
It appears that [Spacebox](http://spacebox.io) became [Plasso](https://plasso.co) and along the way, I think Spacebox’s certificate must've been retired or something. So visiting the current link shows a “Your connection is not private” error (at least, in Chrome).
This PR updates the README to point to the new Plasso link.
> Update donation link

- README.md
Currently, the link to the guide goes through a redirect or two. This change uses the destination URL directly.
> Update link to getting started guide

- middleman-core/features/cli/preview_server-hook.feature
- middleman-core/fixtures/preview-server-hook-app/config.rb
- middleman-core/fixtures/preview-server-hook-app/source/index.html.erb
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/preview_server.rb
- middleman-core/lib/middleman-core/preview_server/server_information.rb
- middleman-core/lib/middleman-core/preview_server/server_information_callback_proxy.rb
- middleman-core/lib/middleman-core/preview_server/server_url.rb
This addresses #1624. @tdreyno @dlitvakb @bhollis @Arcovion 
1. Move HTTPs to server_information to DRY up code and make it reusable in callback_proxy
2. Add hook
This hook get's the same information which are written to STDERR. The main idea for adding this hook, is to support extensions which use libraries like [launchy](https://github.com/copiousfreetime/launchy) to open the preview server site in your local browser.
> Add "before_server"-hook to preview server in v4

- middleman-core/features/front-matter.feature
- middleman-core/fixtures/frontmatter-app/config.rb
- middleman-core/fixtures/frontmatter-app/source/front-matter-haml.html.haml
- middleman-core/fixtures/frontmatter-neighbor-app/config.rb
- middleman-core/fixtures/frontmatter-settings-neighbor-app/config.rb
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/core_extensions/data.rb
- middleman-core/lib/middleman-core/core_extensions/front_matter.rb
- middleman-core/lib/middleman-core/util/data.rb
Ok so there is weird stuff going on here, testing with `bundle exec cucumber features/front-matter.feature `:
1. Changing `frontmatter_delims` to `Middleman::Application.config[:frontmatter_delims]` in `data.rb:27` still works, I'm pretty sure it didn't when I tried the other day...
2. The `config[:frontmatter_delims][:yaml]` variable is mutated with `config[:frontmatter_delims][:yaml] << %w(\\--- \\---)` in each step; `%w(\\--- \---)` is added every time (this does not affect the validity of the test).
3. It makes no difference if you change it to `config[:frontmatter_delims][:yaml] = [%w(--- ---), %w(--- ...), %w(\\--- \\---)]`, it still ends up being a mess like `{:json=>[[";;;", ";;;"]], :yaml=>[["---", "---"], ["---", "..."], ["\\---", "\\---"], ["\\---", "\\---"], ["\\---", …
> Frontmatter delims

- middleman-core/features/cli/preview_server-hook.feature
- middleman-core/features/cli/preview_server.feature
- middleman-core/fixtures/preview-server-hook-app/config.rb
- middleman-core/fixtures/preview-server-hook-app/source/index.html.erb
- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/preview_server.rb
- middleman-core/lib/middleman-core/preview_server/server_information.rb
- middleman-core/lib/middleman-core/preview_server/server_information_callback_proxy.rb
- middleman-core/lib/middleman-core/preview_server/server_url.rb
This is a backport of the changes in v4 to make the server hook available in v3 as well.
@tdreyno I use v3 for some production environments. I hope to find some time to replace some ruby scripts with an extension using the new hook.
> Add "before_server"-hook to preview server in v3

- middleman-core/lib/middleman-more/core_extensions/default_helpers.rb
Just ran into some issues when running tests on one of my libs after bumping from `3.3.11 -> 3.4` that the `asset_url` method (and others that depend on it) no longer works as expected because they're running outside the context of a resource. Largely this probably isn't too much of an issue, but I could imagine cases trying to fetch urls from an extension or something it would also cause issues.
For an example -- some pseudo code assuming run from an extension:
```ruby
app.asset_url 'site.css', 'stylesheets'
app.asset_url 'site.css', 'stylesheets'
```
This PR rearranges the logic of the method a bit, adding the check for the `current_resource` only when it's needed for relative assets. I went with the "fail loudly and explicitly", I'm happy to change that to just return the path like it …
> Allow asset_url to work outside of a resource context when relative: !true

- middleman-core/lib/middleman-core/util.rb
- middleman-core/spec/middleman-core/util_spec.rb
- middleman-core/spec/spec_helper.rb
- middleman-core/spec/support/given.rb
@tdreyno same as #1686 but for v4. This includes some specs (getting an instance to test with is *way* nicer now) that I think cover all the conditional branches for asset_url.
Also includes a fixture helper for rspec, open to any feedback on that (and I'm crossing fingers travis likes it).
> Allow asset url to work without passing a current_resource (v4)

- middleman-core/lib/middleman-core/sources/source_watcher.rb
Fixes #1631, #1627
In SourceWatcher, add a subroutine to find files which should be considered "also dirty" when a given file is touched.
> Fix SASS partial live reloading

- Gemfile
- middleman-core/features/cli/preview_server.feature
- middleman-core/features/data.feature
- middleman-core/features/step_definitions/queryable_steps.rb
- middleman-core/lib/middleman-core/step_definitions.rb
- middleman-core/lib/middleman-core/step_definitions/builder_steps.rb
- middleman-core/lib/middleman-core/step_definitions/commandline_steps.rb
- middleman-core/lib/middleman-core/step_definitions/middleman_steps.rb
- middleman-core/lib/middleman-core/step_definitions/server_steps.rb
@tdreyno @Arcovion 
1. I'm tired to change the `Gemfile` on each contribution. Since this is backward-compatible I changed it to download the git repository via HTTP to make it work across HTTP proxies
2. This upgrades your test suite to aruba 0.10.x and removes all methods with deprecation warnings. Since changes to ENV are "bundle" with aruba from 0.8.0 or so, I modified all places where ENV is accessed. I also make sure, that changes of CWD are local to the steps to prevent "leaking".
To see if this works across all of your supported platforms, I sent you this PR. Both changes are made in two separate commits.
> Upgrade to aruba 0.10.x [WIP]

- middleman-core/fixtures/asciidoc-app/source/hello-with-title.adoc
- middleman-core/lib/middleman-core/renderers/asciidoc.rb
Middleman-called Asciidoctor instance renders title no matter what. The "showtitle" attribute specified in options in asciidoc.rb is not overrideable. This is very annoying if you have custom header (title gets repeated twice: in your header and start of the body).
At the same time the rest of .asciidoc header is only stored in meta.
@mojavelinux I believe that such behaviour was not intended by design and this PR disables the offending attribute.
> Remove showtitle attribute from asciidoc renderer

- middleman-core/lib/middleman-core/core_extensions/front_matter.rb
I believe this is an accurate assumption to make for a resource – that if it is ignored then it shouldn't be parsed by the front matter extension.
Anything I'm missing on this? Should an resource in an ignored path need to have parsed front matter?
> Skip front matter parsing for ignored resources

- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
I've come across this strange situation in v4 - I'm not sure exactly what provokes it to call this path, but the problem is pretty clear (and I'm surprised Contracts don't catch it):
```
no implicit conversion of Hash into String
/Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.0.0/lib/middleman-core/util.rb:211:in `join'
/Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.0.0/lib/middleman-core/util.rb:211:in `asset_url'
/Users/brh/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.0.0/lib/middleman-core/core_extensions/default_helpers.rb:206:in `asset_url'
/Users/brh/Documents/websites/brh/source/software/dashboard-widgets/index.html.haml:18:in `block in render'
```
The culprit is https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/core_extensions/default_ …
> Error calling Util#asset_url from DefaultHelpers#asset_url

- middleman-core/lib/middleman-core/util.rb
- middleman-core/spec/middleman-core/util_spec.rb
Let's say I'm in some nested subdirectory:
```
/category
/things
index.html
/images
screenshot.png
```
If I add this to `index.html`:
```
= image_tag "images/screenshot.png"
```
I would expect a link to `/category/things/images/screenshot.png`. I swear this used to work. But in v4, I get `/images/images/screenshot.png`.
> relative URLs don't work in image_tag

- Gemfile
- middleman-core/features/support/env.rb
This addresses the findings of @bhollis in #1722. Now `phantomjs` is installed via gem. If `phantomjs` is not installed it's downloaded to `~/.phantomjs`.
> Added phantomjs as gem to make test suite pass

- middleman-core/lib/middleman-core/load_paths.rb
`BUNDLE_GEMFILE` is the location of Gemfile,  In [load_paths.rb][] [line#25][] initialize `BUNDLE_GEMFILE`  to Gemfile's parent directory, because `findup` just return the parent directory of the file we looking. This will cause error:`Gemfile not found`
[load_paths.rb]: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/load_paths.rb
[line#25]: https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/load_paths.rb#L25
> Fixes #1723

- middleman-core/features/asset_hash.feature
- middleman-core/features/asset_host.feature
- middleman-core/features/cache_buster.feature
- middleman-core/features/relative_assets.feature
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
- middleman-core/lib/middleman-core/extensions/asset_host.rb
- middleman-core/lib/middleman-core/extensions/cache_buster.rb
- middleman-core/lib/middleman-core/extensions/relative_assets.rb
- middleman-core/lib/middleman-core/middleware/inline_url_rewriter.rb
This allows for configuring the files that will be skipped when performing URL rewriting on the file content. This differs from the existing `ignore` option, which configures the files that won't have hashes added to the filename.
This stemmed from wanting to improve build times on a project by skipping the URL rewriting phase on some large minified JS files didn't contain any asset URLs. The discussion in https://github.com/middleman/middleman/issues/1563#issuecomment-122045822 also points to another potential use for this (skipping problematic files).
I did discover that it's currently possible to do something similar with a custom middleware, like this:
```ruby
class InlineURLRewriterIgnores
def initialize(app, options= {})
@app = app
end
def call(env)
if(env["PATH_INFO"] =~ …
```
> Add rewrite_ignore option to asset_hash extension

- middleman-core/lib/middleman-core/util.rb
I was seeing encoding errors when placing static `.docx` files in my project. After investigating, I found the issue here. The `mime.include?('xml')` being true didn't mean that my `.docx` file was non-binary.
Many MS Office MIME types match `application/vnd.openxmlformats-officedocument.*` (http://www.sitepoint.com/web-foundations/mime-types-summary-list/).
Let me know if I'm doing something incorrectly though. This type of mime type checking was added 3 years ago. I'm not the first one in three years to add a `.docx` to my middleman site, am I?
> consider all MS Office files to be binary

- middleman-core/lib/middleman-core/application.rb
Not sure if operating outside the two official "modes" of either `:build` or `:server` is supported, but if so this additional method would be convenient.
An example is the Contentful Middleman library (https://github.com/contentful/contentful_middleman), which for V3 had the concept of a `:contentful` environment when the task that pulls content down was run, but has now switched to setting `:contentful` as the mode for V4.
Anyhow, this method is just a convenience but I expected it's existence based on the parallel existence of the `environment?` method.
> Add app method to detect mode

- middleman-core/lib/middleman-core/sources/source_watcher.rb
Ran into an issue today with some testing code that happens to invoke the `Middleman::SourceWatcher#update_path`, which was causing a Contract violation.
Looking closer I discovered that:
* The values stored in `@files.values` are instances of `Middleman::SourceFile` (a struct)
* The `update` method expects to receive an array of `Pathname` objects in the removed_paths parameter
* The `update_path` method was incorrectly passing an array of `SourceFile`s to `update`
To remediate this, this PR:
* Ensures that the value of `removed_paths` sent to `update` is an array of `Pathname`s as it expects
* Adds a Contract to the `add_file_to_cache` and `remove_file_from_cache` which makes it clear that these should be `Middleman::SourceFile`s (this would have made it clearer to me during debugging …
> Use correct type for removed paths passed to update

- middleman-core/lib/middleman-core/extensions/gzip.rb
Proposed fix for #1364 
- Changed event name to :created when reporting created output files
- Added empty string as a second parameter to assign total savings summary as extra param which is printed on [Middleman::Cli::Build#on_event](https://github.com/middleman/middleman/blob/d82ac590db5fbb4f7482aed679acef9646d1c45c/middleman-cli/lib/middleman-cli/build.rb#L107) when event type is :gzip
> Fix gzip extension status output

- middleman-core/lib/middleman-core/core_extensions/data.rb
This is a simple PR but would be immensely useful.
In setting up some RSpec tests for a custom command --where an instance of Middleman::Application is being instantiated directly --  I'm finding I have to jump through hoops to point my data dir at a separate fixtures directory.
It's sort of a chicken and egg problem, where setting it in config.rb is too late, since the data dir has to be processed in order to make data available from within config.rb.
I'd like to propose this simple change which would allow me to define a default via a `MM_DATA_DIR` environment variable and vastly simplify some of the hoops that one is required to jump through to set up the data dir in advance of config.rb.
Thanks!
> Add option for MM_DATA_DIR env var to define :data_dir default value

- middleman-core/lib/middleman-core/extensions/minify_javascript.rb
Previously, this JS would not be minified:
```html
<script async>
console.log("Hi.");
</script>
```
This is because the inline JS minify extension would only compress a bare script tag `<script>` or one that had `text/javascript` somewhere in it. I fixed the check to be a bit more precise.
> Minify inline JS when there are other attributes.

- middleman-core/lib/middleman-core/preview_server.rb
Right now, when `watcher_disable` is true, Middleman doesn't actually disable the watcher, it merely adds a few additional ignore paths. Not sure if there's a reason for this? It seems like not the desired behavior when one sets watcher disable to true.
It'd be great if it *actually* disabled the watcher entirely.
This is sort of a nuclear option, but the advantage of this is that I can implement my own custom watch behavior separately, under my own ready callback.
> Disable file watching completely when watcher_disable is true

- middleman-core/lib/middleman-core/meta_pages/templates/index.html.erb
This displays the Middleman version number on the Middleman Information page ([http://localhost:4567/__middleman/](http://localhost:4567/__middleman/)). I did not add this to the other meta pages (sitemap and configuration).
> show version on Middleman Information page

- middleman-core/lib/middleman-core/rack.rb
This escapes the `path` variable using `escape_html` from `Rack::Utils` to prevent (reflected) [Cross-Site Scripting](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) in 404 (Not Found) pages.
PoC: `http://localhost:9292/123<strong>HTML injected</strong>`.
`escape_html` is a good way to escape HTML from input. I'm not sure what the performance impact of including `Rack::Utils` is, if it even matters. I'm open to suggestions!
I wrote a test but I have no clue where it should go. I verified it though and it passes.
```
Scenario: Escapes HTML when a resource is not found
Given the Server is running at "asset-hash-app"
When I go to "/<p>HTML</p>"
Then I should see "Not Found"
And I should see "&#x2F;&lt;p&gt;HTML&lt;&#x2F;p&gt;"
And I should not see "<p>HTML</p>"
```
> Escape path in 404 (not found) page

- middleman-core/lib/middleman-core/core_extensions/data.rb
- middleman-core/lib/middleman-core/util/data.rb
- middleman-core/spec/middleman-core/core_extensions/data_spec.rb
Once I dug in a little more to get some specs running figured out the path the arrays were able to get in (from `touch_file`) so made all the setters/getters consistent based on what would be possible to get out of Util.recursively_enhance.
Totally cool with changing any of this as you see fit.
will close #1803
> loosen contracts for setting/returning data in Datastore

- middleman-core/features/builder.feature
- middleman-core/fixtures/external-pipeline-error/config.rb
- middleman-core/lib/middleman-core/extensions/external_pipeline.rb
This is to fix an issue where the build continues successfully when the external pipeline fails
> Make build fail when external_pipeline fails

- middleman-core/features/partials.feature
- middleman-core/fixtures/partials-app/source/index_missing.html.erb
- middleman-core/lib/middleman-core/template_context.rb
Removed what looks like a stray debugging line from the code and added a test.
> Ensure that misspelled or missing partials generate an error

- middleman-core/lib/middleman-core/sitemap/store.rb
I was trying to make `middleman-blog` work with middleman version 4.1.2 today. This is the code change I had to make in order to make the two compatible.
The call to `resource.page_id` for a proxy resource involves call to the proxy target's `metadata` which involves looking up the resource by `@store.find_resource_by_path` which fails because `@_lookup_by_path` is not finished re-building at the time of the call.
Splitting these three steps out fixes this problem because `@_lookup_by_path` is complete by the time the proxy resource's `metadata` method is ever called.
I will come back and write a test if that's what it takes to get this PR included. :)
> Fix bug with store rebuilding and proxy resources.

- middleman-core/lib/middleman-core/util/paths.rb
- middleman-core/spec/middleman-core/util_spec.rb
If the relative option is set and the asset is stored in the directory
alongside the resource referencing it, asset_url produces the
wrong path ('../images/image.jpg' rather than just 'image.jpg').
> Fix asset_url and relative option bug.

- middleman-core/lib/middleman-core/extensions/asset_host.rb
Copied the extensions from `asset_hash` helper.
Not a fan of how these extensions are copy and pasted between extensions. I'd like to move `sources` and `exts` into a constant in a different PR so these don't drift apart again. Where is the preferred place to put that constant?
> Add exts to asset_host extension

- middleman-core/lib/middleman-core/preview_server.rb
While the CLI options are working nicely for build, they're currently broken for server, in that `app.config` doesn't reflect anything in `after_config`.
This fix is identical to what's done in `build`, and properly applies things in the server environment.
> Fix server CLI

- middleman-core/middleman-core.gemspec
The dependency "listen" in version >= 3.1 isn't compatible with Ruby < 2.2.
See https://github.com/guard/listen/pull/371
> Incompatibility of listen with Ruby < 2.2

- middleman-cli/lib/middleman-cli/init.rb
This PR replaces git://-protocol in the `middleman init/new`-command through https:// to make it work via HTTP proxies. 
* Using git://-protocol for cloning git repositories does not work via
HTTP proxies. By replacing it with https:// instead it works for more
users. 
* HTTP proxies are quite common in enterprise environments so this PR reduces the barrier for such users.
I would like to use `middleman` behind an HTTP proxy which fails on `middleman init my_project` since it's no possible for git to clone the template.
I ran your test suite for cli_init.feature and it succeeded on my local setup `ruby 2.3.x`.
> Use https:// to clone templates on init

- middleman-core/lib/middleman-core/sitemap/store.rb
Contract said that optional param priority can be only a number.
But the code also handle the boolean as a value to be compatibile
with old versions
Change contract to accept both Num and Bool
> Fix contract for Sitemap::Store.register_resource_list_manipulator

- middleman-core/lib/middleman-core/extensions/minify_css.rb
- middleman-core/lib/middleman-core/extensions/minify_javascript.rb
Just started up a new middleman app today and it looks like `try` isn't being included from the ActiveSupport core extensions, so when I turned on the minify JavaScript and CSS options the build would fail.
> fix method missing `try`

- middleman-core/features/asset_hash.feature
- middleman-core/lib/middleman-core/util/paths.rb
- middleman-core/spec/middleman-core/util_spec.rb
Not sure how long this has been broken (at least since MM 3.3), but if you turn on `:asset_hash`, `asset_url`-based helpers like `image_tag` break because they are looking up a resource based on its destination path, which now contains an asset hash (so they don't ever find it). I think there are cases where the text rewriter later fixes this, but it shows up in a bunch of my sites.
This fix simply looks for the normal path first, which is what you'd be using to reference images and other resources most of the time. A new test will hopefully prevent this from breaking again.
> Fix asset_url with asset_hash

- middleman-core/lib/middleman-core/sources/source_watcher.rb
As @vill pointed out in https://github.com/middleman/middleman/issues/1866#issuecomment-222869287
passing `--watcher-latency=2` fails because the gem `listen` expects `latency` to be an `Fixnum`.
This commit fixes this issue.
> Convert `latency` option to a Fixnum

- middleman-core/features/asset_hash.feature
- middleman-core/fixtures/asset-hash-prefix/config.rb
- middleman-core/fixtures/asset-hash-prefix/lib/middleware.rb
- middleman-core/fixtures/asset-hash-prefix/source/index.html.erb
- middleman-core/fixtures/asset-hash-prefix/source/javascripts/application.js
- middleman-core/fixtures/asset-hash-prefix/source/javascripts/application.js.map
- middleman-core/fixtures/asset-hash-prefix/source/layout.erb
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
This allows manually changing the filename so that fiel header changes
can be reflected on the CDN. E.g. if you turn on crossOrigin serving
(CORS) the asset hash doesn't change, but the CDN cache needs to be
broken in order to pickup the new header.
> Add prefix option to asset_hash

- middleman-core/middleman-core.gemspec
As Rails version 5 is out of beta now, we can start using an updated version of Active Support.
I ran `bundle exec rake test` before and after, and nothing changed so this was surprisingly easy.
> Updating to Active Support version 5

- middleman-core/lib/middleman-core/sources/source_watcher.rb
Both `Array#reject` and `Array#include?` have linear time complexity. This results in quadratic time complexity when `Array#include?` is called within `Array#reject`'s block. Using `Array`'s difference operator gives the same result in linear time.
In a site with ~14,000 files, this drops the time taken by some calls to `SourceWatcher::poll_once!` from ~15 seconds each to just a few milliseconds.
> Eliminate quadratic behavior in SourceWatcher::poll_once!

- middleman-core/lib/middleman-core/sitemap/extensions/ignores.rb
- middleman-core/lib/middleman-core/sitemap/extensions/proxies.rb
- middleman-core/lib/middleman-core/sitemap/resource.rb
- middleman-core/lib/middleman-core/sources.rb
On a site with around 14,000 files and a handful of simple ignore patterns, I was seeing `IgnoreDescriptor::ignored?` account for approximately 6 seconds of middleman's initialization time. This change reduces that time to around 0.6 seconds by:
1. Determining the type of ignore pattern only once per pattern, rather than every time the pattern is used.
2. Caching the normalized paths on `Resource` and `SourceFile`.
> Improve performance of ignoring files

- middleman-core/middleman-core.gemspec
There is no current reason to remove support for 4.2
This now makes for a backwards compatible change whereas before this would
have called for a new major version of middleman-core
Refs #1967
> Allow for activesupport 4.2 again

- Gemfile
- middleman-core/features/asset_host.feature
- middleman-core/lib/middleman-core/extensions/minify_css.rb
- middleman-core/lib/middleman-core/extensions/minify_javascript.rb
- middleman-core/lib/middleman-core/rack.rb
- middleman-core/middleman-core.gemspec
- Bump upper boundary of version for Rack dependency from 2.0 to 3 (exclusive). 
- This allows compatibility with `actionpack 5.0.x` (and thus `rails 5.0.x`) which requires `rack 2.x`, while preserving compatibility with `rails < 5`, which requires `rack 1.x`.
- Bump the minimum version of `sinatra` used in CI testing from `1.4` to `2.0.0.beta2` (inclusive).
See #1983.
> Updates to support Rails 5, Rack 3 and Sinatra 2 (beta)

- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/core_extensions/file_watcher.rb
- middleman-core/lib/middleman-core/sources.rb
- middleman-core/lib/middleman-core/sources/source_watcher.rb
Problem is that `FileWatcher` is created in `before_sitemap` callback which results in default config all the time, no matter what are user's settings for `watcher_disable`, `watcher_force_polling`, `watcher_latency` and `watcher_wait_for_delay`.
This PR fixes it by configuring `SourceWatcher` instance in `FileWatcher`'s `after_configuration` callback.
> Fix source watcher configuration

- Gemfile
addressable is required for middleman init, but was not installed as part of a fresh install of Middleman
> Added addressable to the gemfile

- middleman-core/lib/middleman-core/util/paths.rb
Must use `require 'addressable/uri'`
(it's a weirdness in the adressable gem that you cannot require the 'root')
> Fix addressable require

- Gemfile
- middleman-core/features/page-id.feature
- middleman-core/fixtures/page-id-app/config-proc.rb
- middleman-core/fixtures/page-id-app/source/feed.xml.erb
- middleman-core/fixtures/page-id-app/source/folder/foldern.html.erb
- middleman-core/fixtures/page-id-app/source/implicit.html.erb
- middleman-core/fixtures/page-id-app/source/index.html.erb
- middleman-core/lib/middleman-core/sitemap/resource.rb
- middleman-core/lib/middleman-core/util/paths.rb
Got surprised by this while working on #1466.
We also need to remove `localizable/` and the `.en` from the page id, but I don't know at what level we should do that, resource level or i18n, since this is kind of a shared thing.
> Make .html implicit for page IDs

- middleman-core/lib/middleman-core/preview_server.rb
Server to down, when try to load some bower_components/*.ts files...
```
/Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `require': cannot load such file -- typescript-
node (LoadError)
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/typescript.rb:2:in `<top (required)>'
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `require'
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:243:in `block in lazy_load'
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `each'
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:241:in `lazy_load'
from /Users/c01nd01r/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/mapping.rb:216:in …
```
> Add bower_components ignore

- middleman-core/lib/middleman-core/core_extensions/show_exceptions.rb
Not sure what changed, but `rack/showexceptions` is now `rack/show_exceptions`.
<http://www.rubydoc.info/github/rack/rack/Rack/ShowExceptions>
Adding that underscore makes my exceptions all pretty again, which is useful since I can't ever seem to type things correctly the first time.
> change rack/showexceptions to rack/show_exceptions

- .travis.yml
- middleman-core/lib/middleman-core/application.rb
For some reason Ruby 2.4.0 didn't like `layout: proc do |...|` (but `partials: proc do |...|` right above works fine). I also added Ruby 2.4.0 to the Travis config.
> Fix syntax for Ruby 2.4.0

- .gitignore
- Gemfile
- README.md
- middleman-cli/middleman-cli.gemspec
- middleman-core/fixtures/generator-test/config.rb
- middleman-core/middleman-core.gemspec
- middleman/middleman.gemspec
This is a WIP, as I don’t really know what I’m doing here.
[Compass] is no longer actively maintained, so we should remove it from Middleman.
[Compass]: https://github.com/Compass/compass
> Remove Compass

- middleman-core/features/i18n_link_to.feature
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
There is a bug in the I18n part which does not link paths including a locale suffix (e.g. `foobar.en.html.erb`) correctly. This patch fixes it and also adds tests.
Previously, `link_to "Foobar", "/foobar.html"` created a link to `foobar.html` regardless of the locale if the file was named `foobar.en.html.erb`. Now it creates the correct links to `/:locale/foobar.html`.
Documentation of the locale suffixes feature can be found at [the "Localizing Entire Templates" section](https://middlemanapp.com/advanced/localization/#localizing-entire-templates), but until now it did not work with `link_to`. For details see the tests.
I hope you like it.
> Add support for locale suffixes to link_to

- middleman-core/features/i18n_link_to.feature
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
As mentioned in a [comment](https://github.com/middleman/middleman/issues/1587#issuecomment-135469826) on #1587 and in #1798, fragments and queries are discarded when a path is internationalized. The failing test is part of this PR (see 9d5a27ef562921bb2ffa38163389e67d1f1f7031).
This happened because the path _including_ fragment and query was looked up in the internationalization hash. This resulted in an unsuccessful lookup with a fallback to the non-internationalized path. My fix (see 9c1ca5c85af193a32dffe48ebccfc216aa47c047) is to _only_ internationalize the path and leave the rest of the url untouched.
> I18n: Keep fragment and query in url_for

- README.md
Cleaned up the readme file by removing some periods that may cause issues if raw url is copied.
> Removed periods from sentences ending with a URL

- middleman-core/lib/middleman-core/extension.rb
I'm trying to understand how callbacks changed from Middleman v3 to v4. Is it correct that `before_configuration`, `after_configuration`, `before_build`, `after_build`, and `ready` must be defined as separate methods now, and `before_render` and `after_render` are still methods on `app` in the extension`s `initialize` method?
> clarify callbacks docs

- middleman-core/lib/middleman-core/preview_server.rb
When starting the preview server while the port is already in use, users
get the following error message:
> Port "4567" is in use. This should not have happened. Please start "middleman server" again.
I see two problems with this message:
1. "This should not have happened" makes this error sound like
something scary went wrong, while this is something most middleman
users will run into sooner or later.
2. "Please start "middleman server" again." isn't the best advise, since
trying to start it again won't solve the issue, as there's either
another middleman instance running, or some other process is keeping
the port occupied.
Instead, I'd like to propose this:
> Port 4567 is already in use. This could mean another instance of middleman is already running. Please make sure port 4567 is free …
> Update "Port in use"-message for PreviewServer

- README.md
The RubyInstaller-Devkit link has changed. Updated it.
> Updated RubyInstaller-Devkit link

- middleman-core/lib/middleman-core/template_renderer.rb
Currently the build fails when liquid tries to override the (empty or not existing?) context value data.
cc: https://github.com/middleman/middleman/issues/2083
> allow to override data in context

- middleman-core/middleman-core.gemspec
Currently failing with `activesupport 5.1.1` on travis: https://travis-ci.org/amplified-work/middleman/jobs/243873944
I'm interested in guidance on this issue. There is a single failure with liquid templates:
```
Feature: Support liquid partials
The use of "create_dir" is deprecated. Use "create_directory" instead
== Preferring use of LibSass
Scenario: Rendering liquid                    # features/liquid.feature:3
Given the Server is running at "liquid-app" # lib/middleman-core/step_definitions/server_steps.rb:65
Template local `data` tried to overwrite an existing context value. Please rename the key when passing to `locals`
When I go to "/liquid_master.html"          # lib/middleman-core/step_definitions/server_steps.rb:74
Then I should see "Greetings"               # …
```
> Compat with latest rails/activesupport < 5.2

- Gemfile
therubyracer needed a patch to be compatible with Ruby 2.4.1. When
trying to initialize a middleman project on a machine running Ruby
2.4.1, chances are high that the installation will fail due to
therubyracer.
Fixes #2110
> Depend on therubyracer 0.12.3 or higher

- middleman-core/features/chained_templates.feature
- middleman-core/fixtures/chained-app/source/stylesheets/main.css.scss.erb
- middleman-core/fixtures/chained-app/source/stylesheets/sub.scss
- middleman-core/lib/middleman-core/template_renderer.rb
When handling chained templates, middleman used to remove the path and kept only the file's basename. Template engines which support imports (e.g. less or sass), use the file's path to find files to include. Since the path was removed, imports were not working for chained templates.
This commit changes middleman to keep the full path to the template file and adds a test case, which illustrates the desired behavior.
> Support chained sass (and less) files

- middleman-core/middleman-core.gemspec
- remove fast_blank as it blocks Middleman from being used with JRuby
> remove fast_blank dependency

- middleman-core/lib/middleman-core/builder.rb
JRuby cannot chmod a closed file. MRI can do it either way. Therefore, put chmod statement before statement to close file.
Here's the error from JRuby this patch addresses:
```
closed stream
org/jruby/RubyFile.java:601:in `chmod'
middleman-core/lib/middleman-core/builder.rb:188:in `write_tempfile'
```
> chmod before closing file to fix compatibility with JRuby

- middleman-core/lib/middleman-core/extensions/minify_javascript.rb
As LD-JSON spec is basically a JSON in a <script> tag, the uglifier can compress them as a normal javascript.
> Add LD-JSON to MinifyJavascript content types allowed to be compressed

- middleman-core/lib/middleman-core/util/data.rb
- middleman-core/middleman-core.gemspec
I'm really glad that `backports` was helpful to you.
Now that you only support Ruby 2.2+, that particular backport is no longer needed.
Thanks for middleman btw, I've used it before and hope to use it again soon if I can find the time to migrate again my blog.
> Remove dependency that is no longer useful

- middleman-core/lib/middleman-core/application.rb
- clear lazy map after resolving Tilt templates
- use raw ext to resolve Tilt template
> clear lazy map after resolving Tilt templates

- middleman-core/lib/middleman-core/renderers/haml.rb
Fix https://github.com/middleman/middleman/issues/2087
Haml 5 now uses Temple. Thus we need to follow [Temple's way to support Tilt](https://github.com/judofyr/temple/blob/v0.8.0/lib/temple/templates/tilt.rb#L26-L29).
I had the same modification in Tilt https://github.com/rtomayko/tilt/pull/317, but middleman overrides the method to be not functional. So I applied the same fix and also retrieved `:context` option which is added by middleman.
> Resolve Haml 5 warnings

- middleman-core/lib/middleman-core/extension_manager.rb
Add a lightweight method to check if an extension is active:
```
if app.extensions.active? :google_analytics
```
I often need this in templates. The alternative is to retrieve the extension:
```
if app.extensions[:google_analytics]
```
but this does not clearly communicate intent.
> add ExtensionManager#active? to check if extension is active

- middleman-core/features/partials.feature
- middleman-core/fixtures/partials-app/source/_locals.erb
- middleman-core/fixtures/partials-app/source/locals.html.erb
- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
Since upgrading Middleman past 4.1.0, the partial function has been overwritten in the Middleman::CoreExtensions::DefaultHelpers class to include parent locals (https://github.com/middleman/middleman/commit/95537967316577520ad4a665835edf5d4cd64f48).
However, this has altered the default partial functionality inherited from Padrino. The hash that is now passed through to Padrino is a simple Ruby Hash, but before, it could be a Middleman::Util::EnhancedHash when metadata was passed into locals.
This is problematic as partials could use both Ruby's Hash object and a page's metadata (the Middleman::Util::EnhancedHash object) for locals. With the v4.1.0 implementation, Middleman::Util::EnhancedHash keys are stringified when merged with a Hash, meaning that sometimes we can access locals only …
> Use EnhancedHash for partial locals

- .travis.yml
Use latest version on Travis CI.
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/
> Update version of rubies on Travis CI

- middleman-core/lib/middleman-core/dns_resolver/basic_network_resolver.rb
Fixes issue #1621 for the master branch. It was fixed in pull request  #1625 for the middleman:v3-stable branch but this change did not make it to the master branch.
> Add Errno::ENETUNREACH to exception list in BasicNetworkResolver

- middleman-cli/lib/middleman-cli/templates/extension/Rakefile
I could be wrong, but:
```sh
jsoref$ middleman extension foo; cd foo; curl -O https://raw.githubusercontent.com/middleman/middleman/master/middleman-cli/lib/middleman-cli/templates/extension/Rakefile; sed -i.0 -e 's/# s/s/' *.gemspec; rake
js after_configuration
create  foo/.gitignore
create  foo/Rakefile
create  foo/foo.gemspec
create  foo/Gemfile
create  foo/lib/foo.rb
create  foo/lib/foo/extension.rb
create  foo/features/support/env.rb
create  foo/fixtures
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   299  100   299    0     0   3301      0 --:--:-- --:--:-- --:--:--  3322
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): …
```
> Fix rakefile

- CHANGELOG.md
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
I noticed when building the docs site that extension-based templates (page.jp.html) were being requested twice. This makes i18n prefer the extension over the extensionless form.
> i18n was accidently duplicating requests for extension-based templates

- Gemfile.lock
- middleman-core/middleman-core.gemspec
This is to fix the issue that I opened here:
https://github.com/middleman/middleman/issues/2217
Just bumping i18n version to fix the security vulnerability in 0.7
> bumped i18n version

- Gemfile.lock
- middleman-core/middleman-core.gemspec
Hey! 👋 
I'm the release manager for Bundler and I'm preparing for the upcoming Bundler 2 release. I noticed that `middleman-core` has Bundler locked to `~> 1.1`. This should be removed so that people who only have Bundler 2 installed can install your gem.
You don't have to worry about making sure your `Gemfile.lock` loads with the correct version of Bundler, it will take care of that itself.
Thanks!
> Remove bundler version constraint

- .travis.yml
This PR removes a Travis option which no longer does anything.
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Travis: remove deprecated CI option

- .travis.yml
- Gemfile
- Gemfile.lock
This PR adds Ruby 2.6.0, current latest, to CI.
**Update**: The 2.6.0 build wasn't green, so I updated to the latest RuboCop, which had fixed some issues relating to safe_yaml in Psych on 2.6.0. Then, when I tried to install locally, Nokogiri was pinned at an earlier version
- [Nokogiri CHANGELOG](https://www.nokogiri.org/CHANGELOG.html)
- [RuboCop CHANGELOG](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md)
**Update 2**: Yay, now 2.6.0 is green. 🥗 
The only failure in the allowed section of the CI matrix is 2.4.5, on failing to choose a locale. This, I don't understand. Help?
> CI: Add Ruby 2.6.0 + update rubocop, nokogiri

- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
- middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb
Hello, I was having the same issue as #1601 on Middleman 4.2.1, Windows 10, Ruby 2.3.3. Cherry-picking the changes from #1640 solved the problem on 4.2.1 as well.
> Cherry-pick pull request #1640 to 4.2-stable (Missing Requires)

- CHANGELOG.md
- middleman-cli/lib/middleman-cli/build.rb
When a failure happens in the build step, it's often difficult to debug
with `--verbose` on because the error may have occurred in the middle of
the output.  This option now fails upon first error and shows the error
message to make it easier to diagnose and fix problems.
Closes #1924
> Add --bail option to fail upon first error

- middleman-core/features/asset_hash.feature
- middleman-core/fixtures/asset-hash-remove-filename/config.rb
- middleman-core/fixtures/asset-hash-remove-filename/source/index.html.erb
- middleman-core/fixtures/asset-hash-remove-filename/source/javascripts/application.js
- middleman-core/fixtures/asset-hash-remove-filename/source/javascripts/application.js.map
- middleman-core/fixtures/asset-hash-remove-filename/source/layout.erb
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
Hi. So I added a feature I would like to have. Using the `remove_filename` option on `asset_hash` now creates assets without prefixing the filenames.
With `remove_filename: false` (default): `javascripts/application-4553338c.js`
With `remove_filename: true`: `javascripts/4553338c.js`
If you need any changes, tests or additional documentation, please just comment. Thank you for this great piece of software!
> Feature: Add an option to create asset hashes without using the original filenames as prefix

- middleman-cli/lib/middleman-cli/extension.rb
This PR avoids a YARD warning:
```
lib/middleman-cli/extension.rb:27: [UnknownParam] @param tag has unknown parameter name: name
```
> Drop unknown YARD parameter

- middleman-cli/lib/middleman-cli/build.rb
This PR updates a YARD comment to avoid a warning like:
```
lib/middleman-cli/build.rb:103: [UnknownParam] @param tag has unknown parameter name: contents
```
> Update YARD @param name

- middleman-cli/lib/middleman-cli/templates/extension/gemspec
- middleman-cli/middleman-cli.gemspec
- middleman-core/middleman-core.gemspec
Middleman includes specs and fixtures in a gem.
It seems they don't really serve any useful purpose https://github.com/rubygems/rubygems/issues/735 and for example excluded from [bundler generated gems](https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt#L24-L26).
If excluded they significantly reduce size of the gems
Before
After
> Remove test files from gemspec

- middleman-core/features/i18n_link_to.feature
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
I have found middleman to be quite fragile when working with i18n pages. For example `link_to "This page in German", current_page, locale: :de` often just links to the same English version, for example with i18n paths.
This is due to a buggy implementation of the lookup tables used for the paths. I debugged the issue, added tests and a fix that should prove to be more robust in the field. It also seems to be faster (on my machine).
> Reimplement the i18n lookup table

- CHANGELOG.md
- middleman-core/lib/middleman-core/builder.rb
- middleman-core/lib/middleman-core/dependencies.rb
- middleman-core/spec/middleman-core/dependencies_spec.rb
This allows you to always run with --track-dependencies --only-changed,
and if deps.yml is missing, it will write a new one.
It also fixes a small issue where other types of failure in loading
deps.yml were always treated as a general corruption, because the errors
inherited from StandardError through RuntimeError, so they were
re-raised as the less-specific InvalidDepsYAML.
Closes https://github.com/middleman/middleman/issues/2262.
> Create deps.yml when --only-changed is set

- middleman-core/lib/middleman-core/core_extensions/data/proxies/base.rb
- middleman-core/lib/middleman-core/dns_resolver.rb
```shell
$ cd middleman-core
$ bundle exec rspec spec/middleman-core/dns_resolver_spec.rb
```
```shell
$ cd middleman-core
$ bundle exec rspec spec/middleman-core/data_proxy_spec.rb
```
```
1) Middleman::DnsResolver#names_for when hosts resolver can resolve name should not receive getnames(*(any args)) 0 times
Failure/Error:
def initialize(options_hash = ::Middleman::EMPTY_HASH)
@resolver = options_hash.fetch(:resolver, Resolv::Hosts.new(*hosts_file))
end
NameError:
uninitialized constant Middleman::EMPTY_HASH
```
```
1) Middleman::CoreExtensions::Data::Proxies::HashProxy#data_proxy logs sub array access slices
Failure/Error: ArrayProxy.new(key, data, @data_collection_depth, self)
NameError:
uninitialized constant Middleman::CoreExtensions::Data::Proxies::BaseProxy::ArrayProxy
```
---
So …
> Fix failing spec when run as individually

- middleman-core/lib/middleman-core/rack.rb
- middleman-core/lib/middleman-core/step_definitions/server_steps.rb
- middleman-core/lib/middleman-core/util/paths.rb
URI.escape/unescape is obsoleted.
This methods are following RFC 2396.
However, RFC 2396 was obsoleted by RFC 3986.
* https://tools.ietf.org/html/rfc2396
* https://tools.ietf.org/html/rfc3986
Ruby core team says "Instead, use CGI.escape, URI.encode_www_form or URI.encode_www_form_component" but those methods are incompatible between URI.escape/unescape.
So, I choose WEBrick::HTTPUtils.escape/unescape instead, its compatible with URI.escape/unescape.
We need take off this obsoleted rfc dependent behavior in the future.
It shows many warning messages in Ruby 2.7.
> URI.decode/encode is obsoleted. Use WEBrick::HTTPUtils.escape/unescape

- middleman-core/lib/middleman-core/step_definitions/commandline_steps.rb
Those four APIs are now deprecated.
So I replaced to the new APIs.
1. `#run`
-  https://github.com/cucumber/aruba/commit/507b353b678b
1. `#set_env`
- https://github.com/cucumber/aruba/commit/663991ec7
1. `#current_dir`
- https://github.com/cucumber/aruba/commit/802c4ec242
1. `#announcer`
- https://github.com/cucumber/aruba/commit/7f8a155c89
> Replace aruba's deprecated method to the new method

- Gemfile.lock
- middleman-cli/features/support/env.rb
- middleman-core/features/support/env.rb
- middleman-core/lib/middleman-core.rb
- middleman-core/middleman-core.gemspec
- middleman-core/spec/spec_helper.rb
This resolves #2314 by removing Backports altogether.
- Removed dependency on Backports.
I ran all tests with Ruby 2.5.0 and they passed, so I would think Backports might not be needed anymore after all. If you know of places where it might be needed, we should add tests for that and import the needed backport explicitly.
> Remove Backports

- middleman-core/lib/middleman-core/core_extensions/inline_url_rewriter.rb
When rewriting the body output the string length might change, so after applying rewrites we need to forcibly reset the `Content-Length` header to the actual value.
Note that no tests are present since
a) Tests are pretty minimal for the 4.x branch
b) The 4.x branch is no longer mainline
Closes #2309
> Reset Content-Length header when rewriting bodies

- middleman-core/lib/middleman-core/application.rb
Return value documentation was incorrect. As other Boolean return values are not explicitly documented, I just deleted it.
> Delete erroneous documentation of server? / build?

- middleman-cli/lib/middleman-cli/server.rb
The option was removed in bedf235ff68998c0fd87f7531c860f82381312c2. However, it wasn't deleted from the params hash, so a nil value is always being passed in.
> Remove reference to unused reload_paths option

- Gemfile.lock
- middleman-core/middleman-core.gemspec
Change the maximum version of `activesupport` required to be any `5.x` version, bringing the dependency back inline prior to it being restricted in commit ea2115f3f87d6e881fe9517dc65735c96735faf3.
There is a vulnerability reported in `activesupport` that is fixed in version `5.2.4.3`, which `middleman-core` does not allow to be used due to its `< 5.1` version requirement. The vulnerability is [`CVE-2020-8165`].
Prior to commit ea2115f3f87d6e881fe9517dc65735c96735faf3 any `5.x` version was allowed because the dependency was defined as `~> 5.0`, however in that commit that intended to loosen the minimum dependency it appears the maximum dependency was tightened. There is no explanation in the commit or its related PR #1976 about this so it could have been an accident.
Fix #2326 …
> Loosen activesupport dependence for security fix

- middleman-core/features/redirects.feature
- middleman-core/fixtures/redirect-app/config.rb
- middleman-core/lib/middleman-core/builder.rb
This is currently broken in master. Before looking further into it myself, I wonder if anyone else who is more familiar with the codebase can take a quick look, and see if it is something obvious?
Regarding my implementation of the test, I noticed that while the redirect feature makes use of the step
```
And a file named "config.rb" with:
"""
redirect "hello.html", to: "world.html"
"""
```
It seems impossible to make use of this when building an an app, so I created a new fixture. Given that I have this fixture, does it make sense to convert the rest of the scenarios to use it (i.e., is a using fixtures preferred over using the  `a file named "config.rb" with:` step)?
> Test building of redirects

- middleman-core/lib/middleman-core/sources.rb
It was added in 0e620a1ba194d11b0bb2a90535e05f6d87ec1b12, but never used.
> Remove an unused constant

- middleman-core/lib/middleman-core/extensions/gzip.rb
Without this, running `cucumber features/i18n_preview.feature` would fail.
> Require padrino-helpers as they are used in file

- .travis.yml
This way, we don't need to upgrade our .travis.yml when a new minor version is released.
> Use travis-ci's rvm aliases

- .github/CONTRIBUTING.md
- README.md
Information is duplicated between the two. I think it is simpler to keep the README focused on a Middleman user's perspective, whereas CONTRIBUTING.md can focus on a contributor's perspective.
My motivation for this is that I'd like to later add more extensive documentation about testing Middleman from a contributor's perspective, but doing this in the README seemed like it would bloat it too much.
> Reference contribution guidelines in README

- middleman-cli/spec/middleman/.gitkeep
- middleman/spec/middleman/.gitkeep
It looks like these were just here for historic reasons, but not actually necessary.
> Remove unused files

- middleman-cli/features/preview_server.feature
- middleman-core/lib/middleman-core/core_extensions/data.rb
Resolves #2329. Without this, proxy pages that were passed data as a local weren't being loaded when the data changed.
> Trigger a reload for the preview server when data changes

- middleman-core/features/i18n_link_to.feature
- middleman-core/fixtures/i18n-default-app/config.rb
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
The Internationalization extension is redefining url_for to localize url paths. However, this redefinition was also acting on external urls, causing them to sometimes have an "/index.html" appended to them.
This path uses the presence of a host in the parsed URI object to determine whether or not a URL is "external". This is the same method for determining this as is already used in the base url_for.
> Fix linking of external urls when i18n is enabled

- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
This was from e9968680338100bf9f6f2d96c3c1d129a083c49f, when i18n was being explicitly required by all Middleman apps. The same code is already part of `Middleman::CoreExtensions::Internationalization`, so it looks like when that extension was extracted, deleting it here was forgotten.
> Remove unneeded code

- middleman-core/lib/middleman-core/core_extensions/i18n.rb
- middleman-core/lib/middleman-core/step_definitions.rb
Avoiding having test specific code in the extension simplifies it, and eliminates the possibility it would create a bug in a real Middleman app.
Using `defined?(I18n)` is not strictly required, as the I18n module is currently always present, as it is loaded via requiring 'active_support/all'. However, as that's not immediately apparent, and could theoretically change in the future, I thought it was better to have.
> Move i18n test cleanup code to After block

- middleman/middleman.gemspec
Proposal to update kramdown dependency for security reason in v4 middleman: https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
> Update kramdown to avoid CVE-2020-14001 in v4

- Gemfile
- Gemfile.lock
- middleman/middleman.gemspec
Update to version of kramdown to address high severity vulnerability CVE-2020-14001
> Update version of kramdown to ~> 2.3 to address CVE-2020-14001

- middleman-core/lib/middleman-core/extensions/external_pipeline.rb
External pipeline processes, like `webpack`, stop from SIGINT signal with non-zero exit code. In this case middleman reload (for example after `config.rb` change) will lead to dead whole process (middleman + external pipeline), due to non-zero exit code from pipeline.
Option `ignore_exit_code` allow to notify a middleman external pipeline, that it can ignore exit code for a processes on reload/stop.
> Add ability to external pipeline ignore process exit code

- middleman-core/lib/middleman-core/builder.rb
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
Fixes `warning: URI.escape is obsolete` warnings.
Similar to #2312 and the fix 7c155c2
> Replace URI.escape with WEBrick::HTTPUtils.escape

- .dependabot/config.yml
Avoid too much noise in commit list, hides relevant commits in a heap of (mostly) irrelevant ones.
> Reduce dependabot frequency

- .travis.yml
- Gemfile
- Gemfile.lock
- middleman-core/middleman-core.gemspec
Add dependency on WEBrick in Ruby 3.0 and above as it has been removed from the stdlib.
> Ruby 3.0 support

- .github/workflows/ci.yml
https://github.com/ruby/setup-ruby runs `bundle install`
We can see that the step takes 0 seconds at https://github.com/middleman/middleman/runs/1631653509?check_suite_focus=true
> CI: No need to run bundle install

- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
> Require Rack needed by Padrino helpers like mail_to

- middleman/middleman.gemspec
To solve what's probably the same issue as here: https://github.com/jekyll/jekyll/issues/8523
I've tried roughly this, locally and manually, in order to get middleman to build on ruby 3.0.0.
(I am not really a rubyist. Someone more knowledgeable should definitely double-check this before accepting it.)
> Update middleman.gemspec to rely on webrick explicitly

- Gemfile.lock
- middleman-core/features/asset_hash.feature
- middleman-core/middleman-core.gemspec
Reverts a partial of 7f53a163e8174c65718b34541d1d0677227a0528 (a commit of #2424) to allow users to use Rack 2.2+.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Allow users to use Rack 2.2+

- Gemfile.lock
- middleman-core/middleman-core.gemspec
We can only use activesupport 6.0.x since activesupport 6.1.0+ requires `i18n >= 1.6, < 2`: https://rubygems.org/gems/activesupport/versions/6.1.0
> Allow users to use Active Support 6.0

- middleman-core/lib/middleman-core/preview_server.rb
I tried to use the preview server https. This fails due to an SSL error.
~~~
[2021-07-09 15:48:52] ERROR OpenSSL::SSL::SSLError:
SSL_CTX_use_certificate: ca md too
weak\n\t/usr/local/bundle/gems/webrick-1.7.0/lib/webrick/server.rb:262:in
`initialize'
~~~
Along my way I also fixed a variable which is not set (anymore).
> Fix preview server

- .editorconfig
- middleman-core/lib/middleman-core/meta_pages/assets/colors.css
- middleman-core/lib/middleman-core/meta_pages/assets/config.css
- middleman-core/lib/middleman-core/meta_pages/assets/meta.css
- middleman-core/lib/middleman-core/meta_pages/assets/sitemap.css
- middleman-core/lib/middleman-core/meta_pages/templates/config.html.erb
- middleman-core/lib/middleman-core/meta_pages/templates/index.html.erb
- middleman-core/lib/middleman-core/meta_pages/templates/sitemap.html.erb
Dark is a less intrusive brightness
which makes it a more sensible default.
Make files more XHTML compatible
Remove sitemap.js
Add .css indent_size to .editorconfig
Remove unused css-selectors from colors.css
Move colors to separate file
Create colors.css
Wrap colors in @media(prefers-color-scheme: light)
Add colors.css to meta_pages' config.html.erb
Add colors.css to meta_pages' sitemap.html.erb
Add colors.css to meta_pages' index.html.erb
Add colors from sitemap.css to colors.css
Add colors from config.css to colors.css
Remove colors from sitemap.css
Remove colors from config.css
> Support dark mode color scheme

- middleman-core/lib/middleman-core/sitemap/extensions/traversal.rb
I found when building a large site (Gitlab's Handbook) with a lot of pages, the flame graph was getting stuck quite a bit in the `@store.resources.find` block in `sitemap/extensions/traversal.rb`.
With the change in this MR I was able to decrease the build time from ~3m30s to ~2m20s, a ~33% saving for this specific use case.
> sitemap/traversal: Use compiled regex for performance improvement

- middleman-core/features/i18n_preview.feature
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
I recently noticed that I18n fallbacks looked to be dysfunctional on one of my middleman (4.4.0) websites.
After digging a bit, I think it may be because of a breaking change in the ruby-i18n gem (see https://github.com/ruby-i18n/i18n/pull/415).
I have uncommented some tests (cucumber features) that seem to be actually passing, and which contain one feature that does verify that I18n fallbacks are functional. That feature is indeed fixed by this PR.
> Fix broken i18n fallbacks

- middleman-core/lib/middleman-core/preview_server.rb
_Than_ is used in comparisons as a conjunction (as in "she is younger than I am") and as a preposition ("he is taller than me"). _Then_ indicates time. It is used as an adverb ("I lived in Idaho then"), noun ("we'll have to wait until then"), and adjective ("the then-governor").
> Typo correction "t̵h̵e̵n̵" "than"

- middleman-core/lib/middleman-core/preview_server.rb
- middleman-core/lib/middleman-core/preview_server/webrick.rb
Middleman crashes when trying to start an HTTPS preview server.
```
…/gems/middleman-2a0ec8f71ad3/middleman-core/lib/middleman-core/preview_server/webrick.rb:40:in `setup_webrick':
undefined local variable or method `ssl_certificate' for #<Middleman::PreviewServer::Webrick:0x…> (NameError)
```
When the preview server was refactored in e1b0de9, SSL-related instance variables were left in the original `PreviewServer` class, where the new `PreviewServer::Webrick` can't find them.
`PreviewServer::Webrick.new` now accepts an `ssl_information` hash containing the necessary instance variables from the outer `PreviewServer`.
> Fix HTTPS preview server

- Gemfile.lock
- middleman-core/features/minify_javascript.feature
- middleman-core/lib/middleman-core/extensions/minify_javascript.rb
- middleman-core/middleman-core.gemspec
Reverts middleman/middleman#2531
Deciding to revert for 4.x as the impact on existing projects could be very large. Will instead modify the docs to explain how to enable Terser AND set the default new project template to setup projects with Terser enabled.
> Revert "[branch 4.x] Minify JS: migrate from Uglifier to Terser gem to support ES6"

- .github/workflows/ci.yml
As `3.0` is interpreted as `3`, we should use `'3.0'` instead here.
`3.1` is not included in this PR as it was not intended in #2427 and users with Ruby 3.1 can/should use Middleman 5.0.rc.XX.
- Fixes up #2427
- Blocks #2552
- Blocks #2556
- Blocks #2554
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
> Use Ruby 3.0.x correctly on CI

- Gemfile.lock
- middleman-core/lib/middleman-core/util.rb
- middleman-core/middleman-core.gemspec
- cf. #2462
`require `active_support/all` should be used instead of `require 'active_support/notifications'` to avoid errors in case of use of activesupport 7.0.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Allow users to use Active Support 7.0 (4.x)

- .github/workflows/ci.yml
We can track errors on CI with a removal of `continue-on-error: true`.
With #2553 and #2557, all jobs with Ruby 2.5 through 3.0 have been green.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
> [4.x] Avoid continue-on-error

- middleman-core/lib/middleman-core/sitemap/resource_list_container.rb
Allow `Middleman::Sitemap::ResourceListContainer` to delegate `each_with_index`.
For example, [middleman-search 0.10.0 gem](https://rubygems.org/gems/middleman-search/versions/0.10.0) uses this delegated method:
https://github.com/manastech/middleman-search/blob/ed9e5254bb554988c755fc40238d9e9f67b20abe/lib/middleman-search/search-index-resource.rb#L80
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Allow Middleman::Sitemap::ResourceListContainer to delegate each_with_index

- Gemfile.lock
- middleman-core/middleman-core.gemspec
Backports 936d19c from master branch to 4.x branch for middleman-core dependency for [listen](https://rubygems.org/gems/listen) `~> 3.0` and [contracts](https://rubygems.org/gems/contracts) `~> 0.13`.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
> [4.x] Backport 936d19c to middleman core dependency

- middleman/middleman.gemspec
6.0 introduces breaking changes. Lock haml to <6 for now to keep Middleman working. Fixes #2569.
> Lock haml to < 6.0

- middleman-core/lib/middleman-core/extensions/lorem.rb
change supplier for image placeholder since placeholder.it doesn't exist any longer. related to issue [#2540](https://github.com/middleman/middleman/issues/2540)
> change placeholder.it to dummyimage.com

- middleman-core/features/i18n_link_to.feature
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
Backport of #2263 (reimplementation of i18n lookup table) to 4.x branch, including a fix for issue #2594, which was introduced by the referenced PR.
Fixes #2280, fixes #2592.
> Backport of i18n lookup table changes to 4.x, fixes misc url_for issues

- middleman-core/lib/middleman-core/extensions/external_pipeline.rb
Port of #2353 to `v4.x` branch.
> External pipeline: add option to ignore process exit code

- middleman-core/features/i18n_builder.feature
- middleman-core/fixtures/i18n-test-app/locales/en.yml
- middleman-core/fixtures/i18n-test-app/source/localizable/fallback.html.erb
- middleman-core/lib/middleman-core/core_extensions/i18n.rb
Backport of #2602 to the 4.x branch.
Fixes #2596 in the 4.x branch.
> Fix 18n fallback when "mount_at_root" is false (4.x)

- middleman-core/lib/middleman-core/builder.rb
- middleman-core/lib/middleman-core/extensions/asset_hash.rb
- middleman-core/lib/middleman-core/rack.rb
- middleman-core/lib/middleman-core/step_definitions/server_steps.rb
- middleman-core/lib/middleman-core/util/paths.rb
This is a backport of 433a4242e411e9f70077aeff5fca51f68b2d0120 from master, but removing the unrelated changes in the Gemfile.lock.
I particularly need this because the use of  `WEBrick::HTTPUtils.unescape` (introduced in 7c155c298a445f1cc2fb0154721cee260ba333a8) is not totally compatible with `URI.decode`, that was used before, because it does not support unicode chars in the URL. 
`Addressable::URI.unencode`, already in `master`, works as expected. Ir would be great to backport that change to this branch (`4.x`).
> Use Addressable instead of Webrick for encode/unencode

- .github/workflows/ci.yml
- middleman-cli/.simplecov
- middleman-core/.simplecov
- middleman-core/lib/middleman-core/util/data.rb
- middleman/.simplecov
This PR adds Ruby 3.1 to the continuous integration tests, and fixes issue #2614, so that Middleman will work with Ruby 3.1.
Support for older versions of Ruby is retained; a bit of messing around is needed with the arguments to `YAML.safe_load` but otherwise things work fine.
Closes #2614.
> Add support for Ruby 3.1

- middleman-core/features/front-matter.feature
- middleman-core/lib/middleman-core/util/data.rb
For platforms that use YAML::safe_load we have to say which types are supported otherwise the data is rejected when loaded.  In adding ruby 3.1 support (see #2635) we allowed Date and Symbol classes, however in the 5.x branch we support Date, DateTime, Time, Symbol and Regexp by default (see #2528 - specifically 74b01d768b568fd35d163390ead59ad2a09bddd2).  This commit brings the same set of types into the 4.x branch.
We use middleman for the [lrug.org](https://github.com/lrug/lrug.org) site and while exploring upgrading to ruby 3.2 everything broke because we have timestamps in the front matter.  The simplest solution (short of us rewriting all our frontmatter) seems to be extending the support already present in 4.x to allow a few more types that YAML will automatically extract if you let …
> Support more types being extracted from YAML

- .github/stale.yml
Ported from MM v5 branch, which was `main` branch some months ago: https://github.com/middleman/middleman/blob/5.x/.github/stale.yml
> Enable stale bot again (ported from MM v5 branch)

- Gemfile.lock
- middleman-core/middleman-core.gemspec
This patch simply removes contracts dependency version restriction. Since our codebase now runs on any released contracts versions since #2667.
resolves #2685
> Unlock contracts version restriction

- middleman-core/lib/middleman-core/rack.rb
Change rack headers to lowercase, as Rack::Lint now checks that headers are downcased, causing middleman to fail when downloading files such as images while running the server locally.
See also https://github.com/rack/rack/issues/1592
> Downcase rack headers

- Gemfile
- Gemfile.lock
Since now the minor Ruby version is 2.7, we can actually remove those gems added to test old Rubies.
> Gemfile cleanup: these gems were added to test old Rubies

- Gemfile.lock
- middleman-core/features/minify_javascript.feature
- middleman-core/features/support/env.rb
- middleman-core/middleman-core.gemspec
Haml 6 is supported by middleman's main branch, however, it became uninstallable since https://github.com/middleman/middleman/commit/6bf52366abf0ca89549e38b4873b701c66032f44.
Instead, the dependency from `middleman.gemspec` should've been preserved.
> Relax haml dependency to allow haml 5 and 6

- Gemfile.lock
- middleman-core/lib/middleman-core/renderers/erb.rb
- middleman-core/middleman-core.gemspec
Tilt 2.5 removed the erubis template. The maintained template is erubi.
See https://github.com/jeremyevans/tilt/blob/17af3a300ce4bcc79a93901ade7b2e48b6105cbf/docs/TEMPLATES.md#erubi.
> Support tilt 2.5

- middleman-core/lib/middleman-core/application.rb
- middleman-core/lib/middleman-core/sources/source_watcher.rb
- middleman-core/lib/middleman-core/util/paths.rb
When using tilt 2.5, you get a lot of deprecation messages like this:
```
Lazy loading of org templates is deprecated and will be removed in Tilt 3.  Require org-ruby manually.
```
And similarly with many other templates.
This change seems to fix the problem by not eagerly looping through all templates to remove the ones not available.
`:Tilt.default_mapping.lazy_map` is explicitly documented as [private](https://github.com/jeremyevans/tilt/blob/17af3a300ce4bcc79a93901ade7b2e48b6105cbf/lib/tilt/mapping.rb#L128-L129), so not using that seems like a good change too.
> Fix tilt 2.5 deprecations

- middleman-core/features/preview_changes.feature
- middleman-core/lib/middleman-core/file_renderer.rb
The ERB engine was switched to Erubi recently. The Erubi template modifies template data in-place, when it has apostrophes. Since the data we pass to the template holds a reference to the front matter file cache, it will be modified for the subsequent request.
We need to pass a copy instead.
> Fix erb preview regression

- middleman-core/lib/middleman-core/template_renderer.rb
I get a bunch of warnings like the following when building my project:
> Haml::TempleEngine: Option :lang is invalid
If the option is invalid, then don't pass it.
> Fix invalid option haml warnings

- middleman-core/lib/middleman-core/renderers/erb.rb
- middleman-core/lib/middleman-core/renderers/haml.rb
- middleman-core/lib/middleman-core/renderers/kramdown.rb
- middleman-core/lib/middleman-core/renderers/redcarpet.rb
- middleman-core/lib/middleman-core/renderers/sass.rb
This addresses test failures in https://github.com/middleman/middleman-blog/pull/390.
> Respect configured encoding when rendering erb templates

- middleman-core/middleman-core.gemspec
As mentioned in https://github.com/middleman/middleman/issues/2788 a fresh install of Middleman breaks when trying to use the CLI to create a new project. This PR adds `concurrent-ruby-1.3.4` as a dependency to `middleman-core` to address the issue as described in https://github.com/alphagov/tech-docs-gem/commit/a7dc7dc409ec127a6a951f5c1d9c11833aa9a86a
Verified that this fixes the issue with the CLI on a locally built and installed gem.
> Add concurrent-ruby-1.3.4 as a dependency to address issues with activesupport

- middleman-core/lib/middleman-core/util.rb
- middleman-core/middleman-core.gemspec
The missing logger require is fixed in activesupport v8 or higher. And middleman can be used with Rails 8 as long as Ruby 3.2 or higher is used.
So add the missing logger dependency whenever activesupport is not modern enough, and old Ruby is used.
Users of more modern rubies may still run into the issue, but in that case the preferred fix is to upgrade activesupport.
> Workaround activesupport issue

- Gemfile.lock
- middleman-cli/lib/middleman-cli/init.rb
- middleman-cli/middleman-cli.gemspec
In https://github.com/middleman/middleman/commit/ad0e0ee9ba5e017e4f3f1cc861f4fa2a4c04f198 thor was locked at `< 1.3.0` due to #2665 and #2666 .
At root, the issue is because of https://github.com/rails/thor/releases/tag/v1.3.0 and the changes in https://github.com/rails/thor/pull/754 (and related commits such as https://github.com/rails/thor/commit/a601ca9342729350529ee8235abdf9447e77474e) regarding the way Thor 1.3 locates namespaces/classes/commands.
What happens currently is that Thor 1.3 gets completely confused and determines `klass = nil`, `command = middleman`, hence the error `'invoke': Missing Thor class for invoke middleman:generator (RuntimeError)`.
It seems to be that the namespace/class location logic no longer works the same way if the `invoke` instruction does not have the …
> Allow upgrade to thor 1.3.x by correcting `init` behaviour

- middleman-core/lib/middleman-core/meta_pages.rb
Since Rack 3 is more strict about it.
Fixes #2838.
> Use lowercase headers in preview app

- middleman-core/features/image_srcset_paths.feature
- middleman-core/fixtures/image-srcset-paths-app/image-srcset-paths.html.erb
- middleman-core/lib/middleman-core/core_extensions/default_helpers.rb
I've stumbled upon a problem where if you write a syntaxically correct srcset for fixed size with implicit `1x` descriptor that can be omitted ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Responsive_images#resolution_switching_same_size_different_resolutions)), middleman crashes when opening the page because ruby cannot concat string with `nil` and throws an error. This fix allows for implicit descriptors in `srcset` while using `image_tag`.
> Fix implicit 1x scale in srcset crashing middleman
