middleman/middleman

middleman-core/lib/middleman-core/rack.rb
404 now shows full path (similar to url).
=> Fix 404 for sub-mounted apps

README.md
=> Update copyright date README

middleman-core/lib/middleman-core/extensions/gzip.rb
Another suggestion :)
Useful for deployment to S3 together with gzip content-encoding.
=> Add :overwrite option to gzip

.rubocop.yml, middleman-core/lib/middleman-core/core_extensions/front_matter.rb, middleman-core/lib/middleman-core/extensions.rb, middleman-core/lib/middleman-core/renderers/kramdown.rb, middleman-core/lib/middleman-core/renderers/redcarpet.rb, middleman-core/lib/middleman-core/sitemap/extensions/ignores.rb, middleman-core/lib/middleman-core/sitemap/extensions/proxies.rb, middleman-core/lib/middleman-core/sitemap/extensions/redirects.rb, middleman-core/lib/middleman-more/core_extensions/default_helpers.rb, middleman-core/lib/middleman-more/core_extensions/i18n.rb
I "discovered" some rubocop offenses. This PR fixes them.
=> Fix rubocop offenses

middleman-core/lib/middleman-core/templates/shared/config.tt
=> Fix proxy pages link in config template

middleman-core/features/cli_init.feature
* using Middleman directory
* using github
* user/repository
* user/repository#branch
* using full path
* contains "://"
* contains "git@"
=> Add test to `$ middleman init` using tmeplate

middleman-core/lib/middleman-core/templates/default/source/layouts/layout.erb
And also add a newline to the end of the file.
=> Remove spaces on empty lines in default layout.erb

middleman-core/features/extension_hooks.feature, middleman-core/fixtures/extension-hooks-app/config.rb, middleman-core/fixtures/extension-hooks-app/source/index.html.erb, middleman-core/lib/middleman-core/file_renderer.rb
- 'before_render' hook is called twice.
- add simple cucumber test about some hooks.
=> fixed 'after_render' hook is not work.

middleman-core/lib/middleman-core/preview_server.rb
We now use a modified copy of Webrick's `create_self_signed_certificate` that generates a different certificate serial number each time (based on the current time). This avoids an error in Firefox when we serve a certificate with different details but the same serial: it throws up a `sec_error_reused_issuer_and_serial` error and refuses to let you accept the certificate. Our modified version also avoids printing garbage to `$stderr`.
=> Create our own self-signed certs, rather than letting Webrick do it for us

middleman-core/features/redirects.feature, middleman-core/lib/middleman-core/sitemap/extensions/redirects.rb
See https://support.google.com/webmasters/answer/139066
=> Add rel=canonical URL to default RedirectResource template

.rubocop.yml, middleman-core/lib/middleman-core/cli/extension.rb, middleman-core/lib/middleman-core/configuration.rb, middleman-core/lib/middleman-core/core_extensions/rendering.rb, middleman-core/lib/middleman-core/extension.rb, middleman-core/lib/middleman-core/sitemap/extensions/proxies.rb, middleman-core/lib/middleman-more/core_extensions/default_helpers.rb, middleman-core/lib/middleman-more/core_extensions/i18n.rb, middleman-core/lib/middleman-more/extensions/lorem.rb, middleman-core/lib/middleman-more/extensions/relative_assets.rb
Hey,
This fixes most Rubocop warnings, and I removed the invalid Rubocop blocks in `rubocop.yml`. 
Please check it out, thanks!
=> Fix rubocop warnings

Gemfile
Let's try this one to get rid of https://github.com/middleman/middleman/pull/1528#issuecomment-128084209
=> Bump version of cucumber

middleman-core/lib/middleman-core/cli/server.rb
There, now I can say I contributed to Middleman!
=> Fix typo in server CLI.

middleman-core/lib/middleman-core/util/data.rb
Do not merge.
Doesn't work yet, idk why... ¯\\\_(ツ)_/¯
Will wait till the tests are working and then figure out where I went wrong.
=> Refactor frontmatter parsing, closes #1603

middleman-core/lib/middleman-core/util/data.rb
When I saw [this code](https://github.com/middleman/middleman/blob/409a892da707aab0eef848ae79fc7ad97700199d/middleman-core/lib/middleman-core/util/data.rb#L49-L53) checking for `coding: UTF-8` I thought it looked fragile and decided to just ignore everything before the frontmatter in #1604. I've added the check back in here as that didn't work.
=> Fix frontmatter parsing changes from #1608

middleman-core/lib/middleman-core/cli.rb, middleman-core/lib/middleman-core/configuration.rb, middleman-core/lib/middleman-core/core_extensions/rendering.rb, middleman-core/lib/middleman-core/core_extensions/show_exceptions.rb, middleman-core/lib/middleman-core/meta_pages/sitemap_tree.rb, middleman-core/lib/middleman-core/preview_server.rb, middleman-core/lib/middleman-core/preview_server/server_information.rb, middleman-core/lib/middleman-core/renderers/liquid.rb, middleman-core/lib/middleman-core/sitemap/extensions/content_type.rb, middleman-core/lib/middleman-core/sitemap/store.rb, middleman-core/lib/middleman-core/util.rb, middleman-core/lib/middleman-more/extensions/cache_buster.rb
Fixed some typos in the comments.
=> Fixed typos.

middleman-core/lib/middleman-core/dns_resolver/basic_network_resolver.rb
=> Add Errno::ENETUNREACH to exception list in BasicNetworkResolver

middleman-core/lib/middleman-core/meta_pages/sitemap_resource.rb, middleman-core/lib/middleman-more/core_extensions/default_helpers.rb
=> Add some requires to help #1601

middleman-core/lib/middleman-more/core_extensions/default_helpers.rb
=> Add missing require to default_helpers.rb

CONTRIBUTING.md
Sorry. I made the change directly via website.
=> Add warning to contributing.md

CONTRIBUTING.md
@tdreyno Add the warning to CONTRIBUTING.md in v4 as well.
=> Add warning for master as well

CHANGELOG.md, middleman-cli/lib/middleman-cli/server.rb, middleman-core/lib/middleman-core/preview_server.rb
@tdreyno Closes #1649 and makes it obsolete. This makes middleman's preview server become a daemon.
=> Make middleman's preview server a daemon

middleman-core/features/i18n_mixed_sources.feature, middleman-core/fixtures/i18n-mixed-sources/config.rb, middleman-core/fixtures/i18n-mixed-sources/locales/en.yml, middleman-core/fixtures/i18n-mixed-sources/locales/es.yml, middleman-core/fixtures/i18n-mixed-sources/source/a/sub.html.erb, middleman-core/fixtures/i18n-mixed-sources/source/b/index.html.erb, middleman-core/fixtures/i18n-mixed-sources/source/index.html.erb, middleman-core/fixtures/i18n-mixed-sources/source/localizable/a/index.html.erb, middleman-core/fixtures/i18n-mixed-sources/source/localizable/b/sub.html.erb, middleman-core/fixtures/i18n-mixed-sources/source/localizable/index.html.erb
=> Test for issue 1709; parent relations with localized and non-localized sources

middleman-core/features/partials.feature, middleman-core/fixtures/partials-app/source/_block.erb, middleman-core/fixtures/partials-app/source/block.html.erb, middleman-core/lib/middleman-core/template_context.rb
=> fix partials used with blocks

middleman-core/features/asset_hash.feature, middleman-core/fixtures/asset-hash-source-map/config.rb, middleman-core/fixtures/asset-hash-source-map/lib/middleware.rb, middleman-core/fixtures/asset-hash-source-map/source/index.html.erb, middleman-core/fixtures/asset-hash-source-map/source/javascripts/application.js, middleman-core/fixtures/asset-hash-source-map/source/javascripts/application.js.map, middleman-core/fixtures/asset-hash-source-map/source/layout.erb, middleman-core/lib/middleman-core/extensions/asset_hash.rb, middleman-core/lib/middleman-core/util/rack.rb
Test included expected usage :)
=> Add sourceMap comment to asset_hash and hash .map files by default

middleman-core/lib/middleman-core/extensions/directory_indexes.rb
Fixes pretty U.R.L.s for xhtml files
=> Added .xhtml

README.md
Minuscule PR, but I noticed from the README that the sprockets repository has changed.
=> Update link in README to sprockets repository.

.gitignore, middleman-core/features/front-matter-neighbor.feature, middleman-core/lib/middleman-core/core_extensions/collections.rb, middleman-core/lib/middleman-core/core_extensions/collections/step_context.rb, middleman-core/lib/middleman-core/core_extensions/data.rb, middleman-core/lib/middleman-core/core_extensions/i18n.rb, middleman-core/lib/middleman-core/extension.rb
=> Make global config access work inside steps

middleman-core/lib/middleman-core/application.rb, middleman-core/lib/middleman-core/extensions/external_pipeline.rb, middleman-core/lib/middleman-core/preview_server.rb, middleman-core/middleman-core.gemspec
=> Allow restarting external-pipeline without orphaning processes

middleman-core/lib/middleman-core/sitemap/resource.rb
=> loosen contract on Resource#source_file to Maybe[String]

middleman-core/lib/middleman-core/template_context.rb
I can't think of anything valid reason other than my specific case, but requiring a current_resource to find a partial just to support relative lookups doesn't seem necessary so I don't think it will hurt to loosen this up a bit.
In my case I found the issue trying to [support rendering partials in a required file](https://github.com/stevenosloan/middleman-sprockets/blob/e8b5cdeab528a48410b40f864324df59ed9e2732/features/test_cases/partial_rendering.feature#L24-L47). As a contrived example, with a file structure something like this:
```
source/
+- javascripts/
|   +- main.js
|   +- lib/
|   |   +- _templates.js.erb
+- partials/
|   +- templates/
|   |   +- _header.mustache.erb
```
Where
- `main.js` has `//= require '_templates'`
- `_templates.js.erb` has `<%= partial …
=> allow partial lookups without a current_resource

middleman-core/features/markdown_redcarpet_in_slim.feature, middleman-core/features/sass_in_slim.feature, middleman-core/lib/middleman-core/renderers/slim.rb, middleman-core/lib/middleman-core/step_definitions/server_steps.rb
Fixes #1925 and perhaps #1152 also.
=> Prevent overwrite of Slim embedded options

middleman-core/lib/middleman-core/sitemap/store.rb
A bit late, but this should do the trick 🎉
Fixes #2011
=> Fix redirect destination lookup

middleman-cli/lib/middleman-cli/init.rb
- look for template in local directory
- use looser check for SSH git URL
=> discover template in local directory if applicable

Gemfile
Fixes some known security vulnerabilities.
=> Gem updates

middleman-core/lib/middleman-core/application.rb
I just fixed a simple misspelling.
=> Fixed Typo

middleman-core/middleman-core.gemspec
=> Rollback contracts dependency to fix #2126

middleman-core/features/helpers_external.feature, middleman-core/lib/middleman-core/core_extensions/external_helpers.rb, middleman-core/lib/middleman-core/step_definitions/server_steps.rb
Replace `require` with `load` in code that reloads `.rb` files.
=> Fixes #1105

Gemfile.lock
see here: https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#security-notes
=> nokogiri update due to CVE

middleman-core/lib/middleman-core/builder.rb, middleman-core/lib/middleman-core/dependencies.rb, middleman-core/lib/middleman-core/file_renderer.rb, middleman-core/lib/middleman-core/inline_url_filter.rb, middleman-core/lib/middleman-core/renderers/sass.rb, middleman-core/lib/middleman-core/sitemap/resource.rb, middleman-core/lib/middleman-core/template_context.rb, middleman-core/lib/middleman-core/template_renderer.rb
Allow things like config, data or i18n deps.
=> Abstract dependencies away from files

middleman-core/lib/middleman-core/builder.rb, middleman-core/lib/middleman-core/dependencies.rb, middleman-core/lib/middleman-core/dependencies/graph.rb, middleman-core/lib/middleman-core/dependencies/vertices/data_collection_path_vertex.rb, middleman-core/lib/middleman-core/util.rb
Using a lookup hash instead. For #2228
=> Don't linearly search an ever-growing array.

middleman-cli/features/support/env.rb, middleman-core/features/incremental_builds.feature, middleman-core/features/support/env.rb, middleman-core/lib/middleman-core.rb, middleman-core/lib/middleman-core/application.rb, middleman-core/lib/middleman-core/core_extensions/collections/pagination.rb, middleman-core/lib/middleman-core/core_extensions/data/proxies/array.rb, middleman-core/lib/middleman-core/core_extensions/data/proxies/base.rb, middleman-core/lib/middleman-core/core_extensions/data/proxies/hash.rb, middleman-core/lib/middleman-core/core_extensions/default_helpers.rb, middleman-core/lib/middleman-core/core_extensions/front_matter.rb, middleman-core/lib/middleman-core/extension.rb, middleman-core/lib/middleman-core/extensions/minify_css.rb, middleman-core/lib/middleman-core/extensions/minify_javascript.rb, middleman-core/lib/middleman-core/file_renderer.rb, middleman-core/lib/middleman-core/logger.rb, middleman-core/lib/middleman-core/preview_server/information.rb, middleman-core/lib/middleman-core/renderers/erb.rb, middleman-core/lib/middleman-core/renderers/redcarpet.rb, middleman-core/lib/middleman-core/sitemap/store.rb, middleman-core/lib/middleman-core/template_renderer.rb, middleman-core/lib/middleman-core/util.rb, middleman-core/lib/middleman-core/util/uri_templates.rb, middleman-core/spec/spec_helper.rb
=> Centralize active_support integration

.travis.yml
This PR updates the CI matrix to the latest Ruby versions.
=> CI: update matrix

middleman-core/features/i18n_link_to.feature, middleman-core/features/markdown_kramdown.feature, middleman-core/lib/middleman-core/core_extensions/i18n.rb, middleman-core/lib/middleman-core/renderers/kramdown.rb
fixes #2286 
I can only test on my website with v4, which is why the target branch is '4.x'.
=> Fix i18n with anchor v4

middleman-core/features/i18n_link_to.feature, middleman-core/features/markdown_kramdown.feature, middleman-core/lib/middleman-core/core_extensions/i18n.rb, middleman-core/lib/middleman-core/renderers/kramdown.rb
fixes #2286
v5 version of PR #2287
=> Fix i18n with anchor

middleman-core/lib/middleman-core/renderers/slim.rb
=> Allow the full use of Slim::Template.new inside Middleman projects.

middleman-core/lib/middleman-core/core_extensions/front_matter.rb
=> Upgrade spacing in front_matter.rb file.

middleman-core/lib/middleman-core/core_extensions/i18n.rb
=> Fix interpolation in translations for Ruby 3

CHANGELOG.md
Fix: triple space to allow multiline list items
Resolves #2527
=> Chore: update CHANGELOG.md

Gemfile.lock, middleman-core/features/minify_javascript.feature, middleman-core/lib/middleman-core/extensions/minify_javascript.rb, middleman-core/middleman-core.gemspec
ℹ️ **The branch targets v4 branch**
Ref: #2530
=> [branch 4.x] Minify JS: migrate from Uglifier to Terser gem to support ES6

CHANGELOG.md
https://github.com/middleman/middleman/issues/2530#issuecomment-1043563020
=> reflect new default js compressor in changelog [ci skip]

.github/stale.yml
https://github.com/probot/stale
=> Less aggressive stale bot config

middleman-core/lib/middleman-core/extensions/minify_javascript.rb
This breaks client when minify fails
Issue https://github.com/middleman/middleman/issues/2548
=> Update minify_javascript.rb. Remove undefined variable

Gemfile, Gemfile.lock, README.md, middleman-cli/features/support/env.rb, middleman-core/features/support/env.rb, middleman-core/spec/spec_helper.rb
Backport 5f32d3a901684528a30ed23554cacfe1803eefdb to 4.x
=> Remove coveralls from 4.x

Gemfile.lock, middleman-core/fixtures/content-for-app/source/content_for_haml.html.haml, middleman-core/lib/middleman-core/renderers/haml.rb
Following up https://github.com/middleman/middleman/pull/2571, this passes tests with actual Haml 6.
=> Improve Haml 6 support

middleman-core/features/i18n_builder.feature, middleman-core/fixtures/i18n-test-app/locales/en.yml, middleman-core/fixtures/i18n-test-app/source/localizable/fallback.html.erb, middleman-core/lib/middleman-core/core_extensions/i18n.rb
=> Fix 18n fallback when "mount_at_root" is false

middleman-core/features/i18n_link_to.feature, middleman-core/lib/middleman-core/core_extensions/i18n.rb
=> Fix url_for with i18n when "mount_at_root" is false

.github/workflows/ci.yml
Adding Ruby 3.3 to the test matrix. Simply.
=> CI against Ruby 3.3

middleman-core/middleman-core.gemspec
Let's see if the tests pass...
=> Allow users to use newer versions of Active Support

middleman-core/lib/middleman-core/renderers/slim.rb
=> Set generator option only if Slim::VERSION < 5

.github/workflows/ci.yml, Gemfile, Gemfile.lock
This setup seems more sensible and avoid repeating jobs in PRs.
**EXTRA**
- Gemfile cleanup 🧹
- Closes #2731 
- Closes #2730 
@tdreyno Do you agree with this?
=> [CI] optimize created jobs

Gemfile, Gemfile.lock, middleman-core/features/sass_in_slim.feature, middleman-core/lib/middleman-core/renderers/coffee_script.rb, middleman-core/lib/middleman-core/renderers/kramdown.rb, middleman-core/lib/middleman-core/renderers/less.rb, middleman-core/lib/middleman-core/renderers/redcarpet.rb, middleman-core/lib/middleman-core/renderers/sass.rb, middleman-core/lib/middleman-core/renderers/slim.rb, middleman-core/middleman-core.gemspec
Some tests are broken, but opening this as a WIP.
=> Support slim 5

Gemfile, Gemfile.lock
=> [deps] allow newer Active Support versions for Ruby 3.2+

CHANGELOG.md, middleman-core/lib/middleman-core/version.rb
As discussed in https://github.com/middleman/middleman/pull/2777#issuecomment-2597119130 it seems a good moment lo launch a new release.
Full diff: https://github.com/middleman/middleman/compare/v4.5.1...main
=> Prepare new release v4.6.0

middleman-core/lib/middleman-core/renderers/erb.rb
I'd like to add some regression test but it's not trivial for me to do it.
Fixes #2818.
=> Fix regression when visiting sitemap and config page
